### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#13]
Even possible?

**Comment by josephbisch** [comment]
The only reproducible build for something written in Go that I know of is the pluggable transports for the Tor Browser Bundle. Here is the [Linux Gitian descriptor](https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/descriptors/linux/gitian-pluggable-transports.yml). Tor uses the Gitian system developed for Bitcoin Core. They do download the Go software from the official website and use that to build with, rather than build Go itself from source, which would be ideal.

Apparently recent versions of Go use a bootstrap binary for compiling Go from source, so that complicates building Go entirely from source.

**Comment by juniorz** [comment]
Tor Messenger has a ticket for this with some information on Windows and  OS X: https://trac.torproject.org/projects/tor/ticket/10942

**Comment by olabini** [comment]
OK, closing this task now - we will track this in more specific issues, specifically:
#284 
#285 
#286 
#287

**Comment by juniorz** [comment]
This may be relevant to the specific issues. Tor messenger was released with reproducible builds for Windows and macOS (https://trac.torproject.org/projects/tor/ticket/10942).

They use a custom tool (https://people.torproject.org/~boklm/rbm/) to configure the projects to build reproducibly rather than use plain bash. But we can look at their project configuration to bootstrap our builds on macOS and Windows:

https://gitweb.torproject.org/tor-messenger-build.git/tree/projects?id=9accac5b740962c85e044ae620789a156e3c17be

**Comment by juniorz** [comment]
Another reading material: https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/

Debian project diffoscope result: https://tests.reproducible-builds.org/debian/rb-pkg/buster/amd64/diffoscope-results/coyim.html
and a possible fix: https://github.com/golang/go/commit/5bbb98df0960f57dca73cb7640456608d4cc0917
