### ISSUE TITLE
User Flow - Start Security Chat - Error to start OTR

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#136]
If user try to talk with someone that don't have OTR support, we should alert that CoyIM wasn't able to establish OTR.

Maybe we should set a timeout after to send the first query message

**Comment by juniorz** [comment]
The only way to do this seems to be timing out the AKE. Adium does absolutely nothing in this case, because the protocol does not provide any mechanism to detect such things.

Thoughts?

**Comment by olabini** [comment]
Yeah, a timeout seems reasonable to me. What does Pidgin do?

**Comment by juniorz** [comment]
Adium does nothing. It sends the query message (containing a friendly message) and expects the other side to manually reply with an "I got a weird message from you mentioning OTR".

Same with Jitsi.

**Comment by juniorz** [comment]
Same with Gajim and Pidgin.

**Comment by olabini** [comment]
Well, we can do better. =)

**Comment by juniorz** [comment]
I can think about the following failure scenarios while starting an OTR conversation:

1) The sender initiates an OTR conversation (by sending a Query Message) and the receiver does not process the message.

It includes (a) the receiver becoming offline before the message arrives, and (b) the receiver uses an unsupported client. We can identify (a) with xep-0184, if necessary, but the message might be delivered when the receiver is online again (xep-0203). That should not be a problem because DH-commits can be received at any time.

2) The AKE is initiated but not terminated, due never receiving neither RevealSig nor error messages. The other peer may have become offline during the AKE:
- (a) before receiving an AKE messages
- (b) after receiving but before replying an AKE message
- (c) after sending the reply to an AKE message

Keep in mind the scenarios when deciding how to fail when the timeout happens.

**Comment by olabini** [comment]
Hm. Maybe we can't do better. Sigh.
