### ISSUE TITLE
Separate Tor circuits for each account

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#15]

**Comment by juniorz** [comment]
It seems to me that simply configuring Tor via SOCKS5 is not enough to implement this feature, but I could not find a reference on how to do this.

How does TorMessenger and TorBrowser do it?

When the app starts, there is a "Network settings" wizard which allows you to choose between "regular" and "bridge" connection. After that it "connects to Tor network".

What does "connecting to Tor network" actually do? I suspect they have their own Tor process which is controlled via TC (Tor Control) protocol in order to create the circuits, but I'm not sure.

**Comment by juniorz** [comment]
TC protocol: https://gitweb.torproject.org/torspec.git/tree/control-spec.txt

**Comment by juniorz** [comment]
This document outlines how to use the TC protocol: https://svn.torproject.org/svn/torctl/trunk/doc/howto.txt

See sections `1.8. Managing streams and circuits.` and `4. Making a program use Tor`

Also, https://stem.torproject.org/faq.html mentions other controller libraries (including in Go).

**Comment by olabini** [comment]
We don't need the control library or anything. We just need to use different SOCKS usernames. That will separate the streams.

**Comment by juniorz** [comment]
So this is actually about supporting per-account SOCKS config. Nice.

**Comment by olabini** [comment]
More than that, I think we should default each account to have its own SOCKS config.

**Comment by juniorz** [comment]
:ok_hand:

**Comment by juniorz** [comment]
By default, each new account will be configured to have use Tor proxy at `127.0.0.1:9050` with a random user/pass (see 14b8741).

**Comment by olabini** [comment]
Hm. We need to probe whether the user has Tor on 9050 or 9150.
