### ISSUE TITLE
Better solution for Encrypted and Un-Encrypted config files

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#157]
We have two formats of config files,
Encrypted:
```
***suffix is .enc***

{
  params:{
    some params for decryption
  }
  data:"some encrypted data"
}
```
Un-Encrypted:
```
***suffix is not .enc***

{
  accounts:[
    plain text data
  ]
}
```

I propose to have a flag to help define which kind of config it should be:

```
{
  encrypted:true
  params:{
    some params for decryption
  }
  data:"some encrypted data"
}
```
Un-Encrypted:
```
{
  encrypted:false
  accounts:[
    plain text data
  ]
}
```

**Comment by olabini** [comment]
No, I don't like this idea either - because we will end up having to parse it twice, or wrap it in an unnecessary thing. I think the easiest solution is to use the .enc ending always, unless someone uses the command line. If they use the command line option, we also use the .enc ending as a tell. If they want to override that, we provide another command line option --config-file-encrypted=[true/false/yes/no/whatever]
