### ISSUE TITLE
Recognizing network failure still not working

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#161]
When I turn off or restart my tor service, I want CoyIM to immediately recognize this. Currently it takes between 5-10 seconds. That makes no sense. The culprit seems to be that we get this:

[CoyIM] 2015/11/30 13:41:33 /home/olabini/.gopkgs/coyim/src/github.com/twstrike/coyim/xmpp/connection.go:70: xmpp: sending closing stream tag
[CoyIM] 2015/11/30 13:41:33 /home/olabini/.gopkgs/coyim/src/github.com/twstrike/coyim/xmpp/connection.go:70: xmpp: sending closing stream tag
>>> ALERT error reading XMPP message: EOF
>>> ALERT error reading XMPP message: EOF

But we don't seen to be acting on it in the user interface immediately, or something like that.

**Comment by juniorz** [comment]
This is what I assume from your report:

- When you turn off Tor the read socket is instantaneously disconnected.
- `Session#readMessages` fails with `EOF` and `Session#watchStanzas` terminates, closing the session by calling the deferred `Session#Close`.
- `Session#Close` takes a while to finish. This is because `xmpp.Conn#Close` is not instantaneous.

`Conn#Close` closes the XMPP stream. It does not know anything about the socket, so it will close the stream by sending a close tag and waiting for receiving a close tag from the other entity.

Running `s.Conn.Close()` in a goroutine will make `Session.Close()` faster in this case. For the same reasons, we might want to run `s.terminateConversations()` in a goroutine.

For me it has never been instantaneous. For some reason, the Tor socket is kept open for minutes.

**Comment by juniorz** [comment]
Another option is moving `Session#watchStanzas` to `xmpp.Conn`, then we could have more control over when to close the `xmpp.Conn`.

**Comment by juniorz** [comment]
See: 58c6ef988e6afffb0d613a4e8063a3044f2af05f

**Comment by juniorz** [comment]
Is it better now? Can it be closed?

**Comment by tdruiva** [comment]
I tested here, much more faster hehe

![ship it](https://shipitsquirrel.github.io/images/squirrel.png)

**Comment by olabini** [comment]
No, it still takes a long long time for the UI to react - actually, this might be not because of the underlying thing, but because we aren't updating the roster when the connection is closed.

**Comment by olabini** [comment]
This leads to the more general point that we should probably be much more obvious in the UI when the connection is closed.

**Comment by tdruiva** [comment]
Weird, weird, weird....

Well, looks like we have 3 scenarios here:
- for me is automatically
- for @olabini is from 5 to 10 seconds
- for @juniorz is very long....

**Comment by tdruiva** [comment]
> ~~for @juniorz is very long....~~
Ignore this info. His configuration RequiresTor was false.

What do you expect for UI when Tor is turned off?

This screen:
![screenshot from 2015-12-03 11-40-58](https://cloud.githubusercontent.com/assets/1254745/11567189/d04b7daa-99b3-11e5-8fa8-486ef8ddb5c7.png)

Or this one:
![screenshot from 2015-12-03 11-37-59](https://cloud.githubusercontent.com/assets/1254745/11566885/64768ec2-99b2-11e5-9744-69757e6bdafb.png)

If you're expecting the last one, definitely we aren't doing it now.

**Comment by olabini** [comment]
Well, I'm working on fixing this by adding icons next to accounts that show whether we are online or offline instead.

**Comment by olabini** [comment]
I think this can be considered fixed now.
