### ISSUE TITLE
Identify manual steps and make them default and safe

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#17]
This article https://theintercept.com/2015/07/14/communicating-secret-watched/ has a bunch of steps. Almost every single manual one is a place where something can go wrong, so we should identify those places and figure out automatic ways of doing things

**Comment by juniorz** [comment]
This is a braindump after reading the article (in no specific order):

- Creating new chat accounts should be easy and should be done using Tor.
- Use random username and password should be easy.
- Conversations with this account should happen over Tor and only over Tor.
- Different account should use different Tor circuits.
- Do not use a network that can be associated with your real identity (should we give extra points to the security score if we identify a public network - Starbucks?)
- "Don’t give any other identifying information to the chat service." Is this related to the registration? What other kind of information could be leaked?
- Don't leak your habits. Is there anything we can do to prevent patterns regarding login/logout times? Could we warn the user "your conversation pattern is too predictable. take care"? Reading the story of Hammond's arrest I think about using OTR padding SMPs to generate fake traffic during periods of inactivity and prevent correlations with the real world.
- "Be aware of what else you do using your Tor IP address". Should we force setting up the Tor socks using a username and password (to prevent using the same default Tor socks)?
- Disable logging.
- Make it easier to make the first contact. We could provide a "introduction message" template to help people make the first contact. Something like:

> Talk to me via
> romeo@riseup.net | F1C592FC 872B40F3 05A2F1F4 96C98BFD FCE5B62A
> For setup instructions: https://coy.im/setup-private-conversation

- Wipe account button. Accounts should be easily destroyed/abandoned.
- Would it make sense to support accounts configured as `romeo@ijeeynrc6x2uy5ob.onion` instead of `romeo@jabber.calyxinstitute.org`?
- TextSecure has "built-in support for creating anonymous throw-away secret identity accounts" (as the article states). It is a button that creates a disposable account automatically, using a random username and password.
- The article recommends using Tor Browser as a simple way to start the Tor service. Is there anything we can do in this sense to make it easier to setup than `brew install tor` and configure as a service?
- Generate a random user and password for the Tor SOCKS configuration for each account.
- Require encryption and refuse plaintext.
- Random or fixed value for resource.
- We should have an updated version of this article, mentioning how to verify identities using SMP (and explaining what SMP is).

**Comment by olabini** [comment]
I think most of the things we want to do here have their own separate issues by now. Closing it for the moment.
