### ISSUE TITLE
Fingerprint verification flow

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#177]
We should consider what are the actions and messages we present to the user in the following cases:

- I had trusted fingerprint `ABC` for `user@coy.im` but now I'm on a conversation with the same contact with a different fingerprint `DEF`
- I have a new untrusted fingerprint `123` from `user@coy.im` but this fingerprint is already trusted in association with `alice@riseup.net`

**Comment by olabini** [comment]
Since this is a fairly common situation for people between different agents, I think case one is not a problem.
Case two I find highly unlikely, but it's possible that someone can use the same key for more than one user. In those cases we will just treat it separately - which the current changes to fingerprint saving makes easy.
