### ISSUE TITLE
Make get coyim with tag "nocli" as default

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#187]
Currently, when we do `go get github.com/twstrike/coyim` to download coyim we need use the tag `nocli`.

I think would be nice to have `nocli` as default when we wanna get coyim :wink:

**Comment by juniorz** [comment]
It may fix some setup issues discussed in #192 

`go get github.com/twstrike/coyim` will only download the dependencies for the CLI version (the default set of build tags), and result in a broken setup: `go test ./...` will break.

`go get -tags "nocli" github.com/twstrike/coyim` will download the dependencies for the GUI, and does not result in a broken setup.

Both methods require to manually download `gopkg.in/check.v1` even when running `go get -t`. It happens because the package `github.com/twstrike/coyim` has no tests (only their subpackages), so it has no test dependencies to download.

`go get -t github.com/twstrike/coyim/...` will get everything, but I don't think it the obvious choice even for experienced golang developers.

**Comment by juniorz** [comment]
What about moving the CLI to another root package, like `github.com/twstrike/coyim-cli`?

**Comment by tcz001** [comment]
Actually my doubt is why we need to maintain the client version... we're even not using it nor developing it.

**Comment by juniorz** [comment]
We still have to decide what to do with the CLI version.

**Comment by olabini** [comment]
Let's close this task for now, since the main task is already done. We can have a longer discussion about the CLI later.
