### ISSUE TITLE
Unify tor proxy behavior

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#215]
We currently have a bit of a mismatch with proxy behavior - the behavior we have now is good for non-technical end-users, but not so good for power users. The biggest problem with the current approach is that we will only add the Tor proxy information on first usage. So if you add a new account and want to edit the proxy information, you won't see the Tor information there.

We also don't have a good way of recognizing that we have autogenerated usernames and passwords. 

We also don't deal well with more than one proxy right now.

My proposal for how to fix this is that we will add a new protocol scheme called "tor-auto" - when a new account is created we will always add a proxy with data: "tor-auto://" - this will then figure out the right connection information when connecting the first time. It is free to save this information in an extended tor auto section, such as "tor-auto://autogen:autogen@127.0.0.1:9051" - by doing it this way we avoid most of the problems.

We should probably change the account editing details to expose advanced options and proxies as tabs instead of a fold-out. We can do what Enigmail does, and not show those tabs unless a user clicks a "show advanced settings" clickbox.

We should expose proxies in a list where each element can be added or deleted or edited.

**Comment by juniorz** [comment]
> So if you add a new account and want to edit the proxy information, you won't see the Tor information there.

I can't see the problem. The common case (non-technical end-users) is having Tor installed on `127.0.0.1`. If the problem is the user configuring a custom proxy before connecting the first time, the auto-configure code will be skipped if it detects an existing proxy at `127.0.0.1`.

> We also don't deal well with more than one proxy right now.

What is the problem in this case? Is the dialer using the multiple proxies when they are configured?

I'm actually worried about having Tor and other proxies mixed on the same configuration, and I think we should split Tor configuration from proxies configuration.

**Comment by olabini** [comment]
The problem comes when someone wants to edit or change the configuration from the UI - it's messy. I think it makes sense to have it as a proxy.
I think having Tor in the same place as the rest of the proxies make a lot of sense, this ticket is just about cleaning it up a bit so we can edit and modify the settings in a good way.
