### ISSUE TITLE
how to import OTR keys from tor-messenger

### ISSUE THREAD

**Issue by meejah** [twstrike/coyim#273]
It might be nice to have a direct "import from Tor Messenger" button alongside the other OTR key imports. Or at least some documentation pointing out that they are libotr-format files, and live in a fairly-fixed (I believe) spot relative to the base of wherever tor-message was un-tar'd. That place is:

  - `./Messenger/TorMessenger/Data/Browser/profile.default/otr.private_key`
  - `./Messenger/TorMessenger/Data/Browser/profile.default/otr.fingerprints`

**Comment by olabini** [comment]
Is this still true for the latest versions? They used to save profile data in the directory where the thing was expanded, which makes it really hard to find. But I seem to remember they changed that recently.

**Comment by meejah** [comment]
I'm not sure if it's still true; haven't used Tor Messenger since switching to coyim ;)

But at least pointing out in the docs that the "otr.private_key" etc files happen to be libotr-format would have saved me some time. Obviously bonus points if there's an automated way :) 

Also some kind of "yes you can switch from [Tor Messenger, whatever-else, ...] and keep your fingerprints + OTR keys" bullet-point somewhere on the "about" page would be good. This was my first question when I first heard about coyim and was considering trying it...

**Comment by olabini** [comment]
Yeah, we should definitely do something about this! Thanks.

**Comment by olabini** [comment]
Sadly it turns out Tor Messenger stores its profile information inside wherever the archive has been unpacked. That means there is really no way for us to identify where it exists, and we can't automaticlaly find it. In order to improve the situation I added documentation to the key/fingerprint importer mentioning the applications that use the libotr protocol and what those file names are. Right now it's probably the best we can do.
