### ISSUE TITLE
account info lost for seemingly no reason

### ISSUE THREAD

**Issue by alisonLFP** [twstrike/coyim#283]
just logged into coyim and it made me re-add my xmpp account info out of nowhere. this was within an hour of using it without issue. I didn't make any change to the client. It's assigned me a new OTR fp and everything.

**Comment by olabini** [comment]
Ugh. Terribly sorry about that. Is this with the 0.2 from the website? Any other information you can give that would help?

**Comment by xSmurf** [comment]
I've seen that happen once with the sgos build, I sort of brushed it off blaming OZ though I've never seen OZ do anything like that. I've also not seen this happen again with any recent builds.

@alisonLFP can you specify if this is the build from the website or in SGOS?

**Comment by olabini** [comment]
It would be really helpful if you can specify a few more things. 
- What OS
- Encrypted config storage or not
- Can you look in ~/.config/coyim and tell me what file(s) are in there?
- Do you remember anything about what you were doing just before closing the client before starting it up again?
- Do you run with the -debug flag? If so, do you have any output from it?
- How many accounts do you have configured? Anything strange about them?

**Comment by olabini** [comment]
Obviously, all this can be invasive, so if you don't feel comfortable sharing any of this, that's fine - or if you want to send a private email with the information that's fine as well.

**Comment by olabini** [comment]
Actually, looking through the code for 0.2, there is one thing that can happen - if for example you change the "Connect on Startup", "Merge accounts" or any of the other checkboxes, and then quickly change it back, it is not impossible that the system will potentially start two saves at the same time - and if that happens, there are some unlucky interleavings that might manage to remove the config file. Stupid.

This has been fixed in the current code base, by adding a lock around all IO operations to the config file, so it shouldn't be possible any more. I'll close the ticket for now. Thanks for the report.

**Comment by alisonLFP** [comment]
hi, this just happened again. I did not make any change to CoyIM and it had been working fine a few minutes prior. Oz has not been working for me, so it was outside of the Oz sandbox -- not sure if that's relevant or not. I don't see any version info anymore and David tells me that this is the "subgraph non-version version" :). Let me know what other info I can provide.

**Comment by olabini** [comment]
Hm, I'm terribly sorry about that. I don't know what the subgraph non-version version is about. 
@dma - care to expand on which version it is based?

The questions in the above comment are still valid, and could help find the reason.

**Comment by olabini** [comment]
Haven't seen anything about this for a few months. I'll close it for now.
