### ISSUE TITLE
Remove tags from message history

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#295]
If I'm chatting with someone that is using Pidgin, I receive tags in the message.
I think would be good if we remove this tags before displaying the message to user.

![screenshot from 2016-03-24 10-51-11](https://cloud.githubusercontent.com/assets/1254745/14023186/3751557e-f1b1-11e5-9948-cd3c8f1a515b.png)

**Comment by olabini** [comment]
This behavior was reverted in #276 . I guess we need to revisit. But sending HTML isn't part of any standard as far as I know.

**Comment by xSmurf** [comment]
Before I expand on this, here's the XEP: https://xmpp.org/extensions/xep-0071.html

**Comment by xSmurf** [comment]
Sorry for the confusion that's entirely on me. I had expressed in another ticket that the HTML was included as a sibling of <body/>, but the XEP clearly specifies that is a child of <body/>.

**Comment by xSmurf** [comment]
> In Jabber/XMPP communications, the meaning (as opposed to markup) of the message MUST always be represented as best as possible in the normal <body/> child element or elements of the <message/> stanza qualified by the 'jabber:client' (or 'jabber:server') namespace. Lightweight text markup is then provided within an <html/> element qualified by the 'http://jabber.org/protocol/xhtml-im' namespace.

**Comment by olabini** [comment]
OK, after some discussion the status is this. None of the XEPs are relevant because most of the content will be OTR encrypted. It seems Pidgin encrypts the html version, not the plaintext version. Thus there's no XMPP way of dealing nicely with this.
Some clients (Gajim) - strip everything html looking. That seems a bit too severe. So let's do an inbetween where we strip the most common presentation tags, but nothing else.

**Comment by olabini** [comment]
The suggesting from @xSmurf is to use the list of tags in XEP-71 plus font.
