### ISSUE TITLE
Sign releases and git commits.

### ISSUE THREAD

**Issue by qubenix** [twstrike/coyim#325]
Please sign releases and git commits, preferably with an offline signing key.

**Comment by olabini** [comment]
Thanks for the feedback. As a matter of fact, all of my git commits are already signed.
However, when it comes to signing releases, we are planning to go for reproducible builds in order to avoid the need for one "big" master signing key. There are several issues opened to track this already.

We have not focused on signing right now, since the project is still extremely young, pre-alpha and not recommended for real use.

**Comment by adrelanos** [comment]
6 years later.

Could you please re-consider signing releases?

related:
https://github.com/coyim/coyim/issues/703
