### ISSUE TITLE
Purpose of "Connect on Startup"

### ISSUE THREAD

**Issue by t2d** [twstrike/coyim#336]
What is the purpose of `Account > Connect on Startup`? I have to enable the automatic connection anyway in `Accounts > {Accountname} > Connect automatically`. The other option was confusing me.

**Comment by olabini** [comment]
Yes, I admit they are a bit confusing. We will probably move them somewhere else where we can add some more explanation.

Account > Connect on Startup - when set, CoyIM will automatically connect to all accounts that have been marked as "Connect automatically" - this way you can choose three accounts that should always be connected, but a few others that shouldn't, for example.

**Comment by t2d** [comment]
I think, this should be the default behaviour.
Do not automatically connect any account, unless `Connect automatically` is ticked. This makes the `Connect on Startup` option obsolete.

**Comment by olabini** [comment]
Which should be the default behavior?

The thing is, they provide different capabilities. For example, I want all my accounts to be disconnected and startup. I usually use account A and D and F, so I want them to automatically be connected when I say connect all. Account B and C are sensitive and I only want to connect them under specific circumstances. That's why we have that kind of flexibility.

**Comment by t2d** [comment]
Agreed. Therefore, you would only tick `Connect automatically` for A, D and F, but not B and C.
Default should be: Do not automatically connect any account, unless `Connect automatically?` is ticked in the specific account.

**Comment by olabini** [comment]
I'm a bit confuse dhere.
