### ISSUE TITLE
Double Ratchet Support

### ISSUE THREAD

**Issue by Dyras** [twstrike/coyim#364]
Hi! This program looks great, but I think if you want to have encryption every time, all the time, you should implement the Double Ratchet Algorithm used in Cryptocat and Signal. The biggest flaw with OTR is that both users have to be online at the same time in order for it to be useful. Double Ratchet solves that beautifully.

https://github.com/trevp/double_ratchet/wiki

**Comment by olabini** [comment]
Hi,

Thanks for the interest. But first of all - double ratchet is not what gives Signal the possibility of starting a session with an offline person. That is actually the triple-DH AKE that Axolotl/the Signal protocol uses. The ratcheting is only about what happens when the AKE has already finished.

Second, see #233, #199 for discussion on OMEMO that also supports this - and why we are currently not interested in adding support for another protocol outside of OTR.

**Comment by Dyras** [comment]
Didn't even know OTR4 had that feature, keep up the good work implementing that!

**Comment by olabini** [comment]
OTR4 doesn't exist yet - but we are working on it, and having that kind of support is definitely important.
