### ISSUE TITLE
Signatures and sha2/3 of the binaries

### ISSUE THREAD

**Issue by mrphs** [twstrike/coyim#373]
I noticed the binaries on the website are being distributed from a domain that is not coy.im and you don't provide any signatures or shasum of the binaries. Would it be possible to sign the binaries and add the signatures to the website?

**Comment by olabini** [comment]
Hey

This is completely on purpose - at least the signatures. We don't have full control of the coy.im domain either, and since all the binaries are currently built on Travis and other cloud based providers, putting signatures would kinda give a false sense of security for anyone that sees it.

We want to get to the point - relatively soon - where we have reproducible builds. Once we have that, we can provide signatures that actually have value.

Here are some issues that trace these things:

On signing releases and tags: #325 
On reproducible builds: #13

**Comment by olabini** [comment]
Well, I should have mentioned - for purposes of integrity only, not repudiation or anything, we do have signatures - although those are signed by travis or bintray (don't remember which one) - so you can use it as a better checksum. The links aren't published, but are the same links with ".asc" at the end, so for example https://dl.bintray.com/twstrike/coyim/v0.3.6/linux/amd64/coyim.asc

**Comment by ge-fa** [comment]
It would be nice if at least the git tags could be signed, or more specifically, a detached sig could be uploaded to GitHub. See [this](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) for some more details.

**Comment by olabini** [comment]
@ge-fa thanks for the point. However, the latest two release tags v0.3.7 and v0.3.8 ARE actually signed. I personally prefer to separate the signing of tags from the github workflow, so that anyone using git can verify them. Most commits on CoyIM are also signed.

**Comment by ge-fa** [comment]
Yeah, you're right, and I agree, especially to be independent of the GitHub workflow. However, the tooling in Debian while importing is currently limited; the tools are lacking support to verify git tags, but only detached signatures. I'll work on this during the year.
