### ISSUE TITLE
TLS Certificate verification

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#41]
Including possibility of manually trusting a cert. These are the specific pieces of functionality I think we need:
- [x] Trusting the certificate temporarily
- [x] Setting for manual approval of everything
- [x] Show connection info per account, right click or something
- [x] Look at parents of certs
- [x] Save more than one valid cert
- [x] Pin certs
- [x] Recognize the google situation
- [x] Edit list of saved certs
- [x] Certs are saved per account

**Comment by jubalh** [comment]
That would be pretty cool since when trying to connect to jabber.ccc.de coy tells me:
```
>>> ALERT xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "CA Cert Signing Authority")
```

**Comment by tcz001** [comment]
but it seems to be a 'algorithm unimplemented' according to this log

**Comment by tcz001** [comment]
```
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: D0B089671C98489448420926883A752770E61A64360241E76EF1392BDE1AD161E8755D829F6B7E527C098E5C41D87DC0
    Key-Arg   : None
    Start Time: 1451946131
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
```

https://github.com/golang/go/issues/7758

**Comment by sycamoreone** [comment]
The "x509: cannot verify signature: algorithm unimplemented" error comes from the crypto/x509 package and has nothing to do with the TLS ciphersuites. The problem here is really the missing CA Cert root certificate needed to verify the jabber.ccc.de certificate.

xmpp-client contains some [hard-coded logic](https://github.com/agl/xmpp-client/blob/master/ui.go#L329) for this actually, so it is possible to connect to jabber.ccc.de (for example using the TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 ciphersuite supported both by Go's tls package and by jabber.ccc.de)

**Comment by juniorz** [comment]
@sycamoreone FYI, `coy` has the same code: https://github.com/twstrike/coyim/blob/master/config/certs.go#L165

which is used by the connection policy: https://github.com/twstrike/coyim/blob/master/config/connection_policy.go#L85

Unless the error message reported by @jubalh (which is the error returned by https://golang.org/pkg/crypto/x509/#Certificate.Verify) is very misleading, I would also suspect the problem is the `x509: cannot verify signature: algorithm unimplemented`.

Do you have any additional debug information?

**Comment by tcz001** [comment]
@sycamoreone 
Thanks for infomation, I tried on my xmpp-client *without* system trusting this cacert root class 1 PKI. It's still showing an error
```
 * (10:50AM) Temporarily trusting only CACert root for CCC Jabber server
 * (10:50AM) Making connection to okj7xc6j2szr2y75.onion:5222 via proxy
 * (10:50AM) Starting TLS handshake
 * (10:50AM)   SSL/TLS version: TLS 1.2
 * (10:50AM)   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 * (10:50AM) Failed to connect to XMPP server: xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "CA Cert Signing Authority")
```

**Comment by tcz001** [comment]
But anyway manually trusting a cert is still a good feature we should support,

For the ciphersuite should we create another issue?

**Comment by tcz001** [comment]
The following two lines are not working actually, if I use mac keychain to trust, this problem is solved,
@jubalh can you please provide some more info about your system and RootCA trusts?
I guess it's also a bug of xmpp-client.
```
roots.AddCert(caCertRoot)
xmppConfig.TLSConfig.RootCAs = roots
```

**Comment by sycamoreone** [comment]
This is also a bug in xmpp-client and the problem really is a "missing" algorithm in the x509 package. If one compiles with a recent Go with this patch  https://github.com/golang/go/commit/606d9a7e18c951bb64ea460597894558ff3808c1, one gets this error message instead:

``` xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm MD5-RSA" while trying to verify candidate authority certificate "CA Cert Signing Authority")```

**Comment by sycamoreone** [comment]
Just checked: The hardcoded root certificate really uses the 	MD5WithRSA as SignatureAlgorithm.

**Comment by tcz001** [comment]
@sycamoreone 

Things are bit of complicated now,
xmpp-client is having a bug for this, but the ciphersuit is not the problem here (saying: jabber.ccc.de).

I made a fix for both [xmpp-client](https://github.com/tcz001/xmpp-client/commit/797da607e5ce40bdcfd646a0d03910f0e9d07c4f) and [coyim](https://github.com/twstrike/coyim/commit/8683c50a3d82b58343e0a9d7132d8c080a923589).

But yes, if the algorithm of server only support DHE, it's still a problem.

**Comment by olabini** [comment]
What's the status on this one?

**Comment by tcz001** [comment]
Manually trusting a ca is not done, we just fixed the ccc.de hard coded part.

**Comment by olabini** [comment]
OK, but is there an actual problem with algorithms here?

**Comment by tcz001** [comment]
If the server only supports MD5WithRSA, algorithms is still a problem.

**Comment by olabini** [comment]
And the problem is the Go support, that doesn't support that algorithm? Or is it because we manually restrict the available ciphers?

**Comment by tcz001** [comment]
As @sycamoreone mentioned, golang will return error if it knows insecure algorithm like MD5. But manually trusting a cert won't have that problem I think.

**Comment by olabini** [comment]
OK, but does it do that because we are restricting the algorithms, or is it hardcoded into Golang?

**Comment by tcz001** [comment]
We are restricting [here](https://github.com/twstrike/coyim/blob/master/xmpp/tls.go#L28). the change in golang is just to show more details rather than providing a "algorithm unimplemented"

**Comment by tcz001** [comment]
But Some cases will be treated as InSecureAlgorithm by default.
eg. MD2WithRSA and MD5WithRSA
https://github.com/golang/go/blob/be7544be237b279e45be73963e84ab59916b8ac2/src/crypto/x509/x509.go#L684

**Comment by sycamoreone** [comment]
> As @sycamoreone mentioned, golang will return error if it knows insecure algorithm like MD5. But manually trusting a cert won't have that problem I think.

My analysis wasn't correct. Go indeed won't verify certificates using the MD5WithRSA algorithm used by by the CACert certificate, but this was not the problem here, because the *root* certificate doesn't need to be verified, so the algorithm suite used is [irrelevant](https://github.com/agl/xmpp-client/issues/109#issuecomment-170373450).

The real problem was fixed by @tcz001's patch in https://github.com/twstrike/coyim/issues/41#issuecomment-169074349.

(All of this had nothing to do with allowing people to manually trust a cert. Sorry for having hijacked this issue.)

**Comment by juniorz** [comment]
This issue is about the server's leaf certificate. The idea here is to notify the user when some problem happens with the certificate, interrupt the connection, ask for an action, and then reconnect if necessary.

Which actions make sense?

1. Trust the certificate temporarily and connect.
2. Trust the certificate permanently for this account and connect.
3. Don't connect.

(1) requires allowing `ConnectionPolicy` to create an `xmpp.Config` with a temporary `ServerCertificateSHA256` property rather than loading it from `config.Account#ServerCertificateSHA256`, and then reconnect using this new `ConnectionPolicy`.

(2) requires setting `config.Account#ServerCertificateSHA256` to the target certificate SHA256 hash, and saving the config. After this simply reconnect.

(3) should require no significant change.

**Comment by olabini** [comment]
I think all three should be valid ones. I also know there are situations where more than one certificate is valid - so we might want to move to a list of certificate hashes.

**Comment by iapazmino** [comment]
If we stop connection and ask the user to decide which path to follow aren't we assuming the user is making an informed decision? I'm not sure this would be a correct assumption and would actually be prone to believe the user is just trying to get CoyIM out of the way.

A secure default here, I guess, would be to do not connect and issue the warning. Then, the user would need to enable connection for that server (temporary or permanent) manually.

**Comment by olabini** [comment]
I think we will ignore the parent cert for now.

**Comment by olabini** [comment]
I think we will ignore the parent cert for now.
