### ISSUE TITLE
Check if Tor is running

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#82]
- [ ] When opening CoyIM to check if Tor is running
- [ ] If it's not running notify user
- [ ] Disable all functionalists until have Tor running

**Comment by juniorz** [comment]
After modeling the "account setup wizard" following the "setup user account" flow, it seemed to us that it unnecessarily exposes the user to a lot of technical information (having Tor, your XMPP server might not be the same as your account domain).

We thought about postponing all those decisions to the moment the user choses to connect an account, meaning:

At the moment you choose to connect an account,
 - Check if Tor is running. If it is not warn the user. Should it prevent the user from connecting until it has Tor running?
 - Use the server/port manually added in the account settings, if available.
 - Otherwise, we follow the protocol to discover the domain (first SRV, then use domain at default port)
 - If it fails we ask the user for a domain, explaining why we need it and giving an example ("If your account uses google for email, you may want to try xmpp.google.com"). In this case, we should save this option to the account settings after the connection succeeds.

Creating accounts does not require having Tor running.

cc @olabini

**Comment by juniorz** [comment]
194eaca is the final piece of this. Closing.

**Comment by juniorz** [comment]
Closed by 37f3a8c

**Comment by tdruiva** [comment]
:+1:
